global:
  scrape_interval: 10s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'localhost:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.10.8.159:9100']
        labels:
          name: 'stg-k8s-master'
      - targets: ['10.10.8.211:9100']
        labels:
          name: 'stg-k8s-worker-1'
      - targets: ['10.10.8.176:9100']
        labels:
          name: 'stg-kafka'
          # Others Server ip 